name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event_name,'[no-page]') }}
    steps:
      - uses: actions/checkout@v2 # Only works with v2
      - uses: subosito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          workingDir: escape_wild
          baseHref: /EscapeWild.Flutter/